name: flutter_document_scanner
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  cunning_document_scanner: ^1.1.2
  path: ^1.8.3
  pdf: ^3.10.4
  path_provider: ^2.1.1
  image_editor: ^1.3.0
  flutter_genius_scan: ^4.13.0
  image: ^4.1.3
  carousel_slider: ^4.2.1
  # image_editor_dove: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
